"""Photorefractive two-beam launch and sampling geometry."""

from __future__ import annotations

from dataclasses import dataclass
import math

from lcprop.core.beams import BeamChannel


def _pair(value, *, name: str) -> tuple[float, float]:
    if isinstance(value, (int, float)):
        pair = (float(value), float(value))
    else:
        pair = tuple(float(item) for item in value)
        if len(pair) != 2:
            raise ValueError(f"{name} must be a scalar or length-two sequence")
    return pair


def paraxial_kernel_slope(
    *,
    transverse_phase_gradient_rad_per_um: float,
    wavelength_um: float,
    refractive_index: float,
) -> float:
    """Return the ray slope generated by LCProp's paraxial FFT kernel.

    The kernel phase is ``-pi*dz*wavelength*f_transverse**2/n``. Its group
    delay moves an envelope at ``dx/dz = wavelength*f/n = kx/k_medium``.
    """

    wavelength = float(wavelength_um)
    index = float(refractive_index)
    if wavelength <= 0.0 or index <= 0.0:
        raise ValueError("wavelength_um and refractive_index must be positive")
    k_medium = 2.0 * math.pi * index / wavelength
    return float(transverse_phase_gradient_rad_per_um) / k_medium


def crossing_beam_channels(
    *,
    wavelength_um: float,
    refractive_index: float,
    interaction_length_um: float,
    polar_angles_rad: tuple[float, float],
    azimuths_rad: tuple[float, float],
    waist_x_um: float | tuple[float, float],
    waist_y_um: float | tuple[float, float],
    crossing_x_um: float = 0.0,
    crossing_y_um: float = 0.0,
    crossing_z_um: float | None = None,
    powers_mW: tuple[float, float] | None = None,
    beam_ratio: float | None = None,
    total_power_mW: float = 1.0,
    coherence_group: str = "pr-two-beam",
    names: tuple[str, str] = ("pump", "signal"),
) -> tuple[BeamChannel, BeamChannel]:
    """Construct two channels whose kernel rays meet at a physical point.

    Polar and azimuth angles define ``kx = k_medium*sin(theta)*cos(phi)`` and
    ``ky = k_medium*sin(theta)*sin(phi)``. LCProp's paraxial kernel then moves
    the envelope with slopes ``kx/k_medium`` and ``ky/k_medium``. Launch
    centers are back-projected with those numerical slopes, not ``tan(theta)``.
    """

    length = float(interaction_length_um)
    if not math.isfinite(length) or length <= 0.0:
        raise ValueError("interaction_length_um must be finite and positive")
    z_cross = length / 2.0 if crossing_z_um is None else float(crossing_z_um)
    if not math.isfinite(z_cross) or not 0.0 <= z_cross <= length:
        raise ValueError("crossing_z_um must lie within the interaction region")
    angles = _pair(polar_angles_rad, name="polar_angles_rad")
    azimuths = _pair(azimuths_rad, name="azimuths_rad")
    waists_x = _pair(waist_x_um, name="waist_x_um")
    waists_y = _pair(waist_y_um, name="waist_y_um")
    if any(value <= 0.0 for value in waists_x + waists_y):
        raise ValueError("beam waists must be positive")
    if not isinstance(coherence_group, str) or not coherence_group.strip():
        raise ValueError("coherence_group must be non-empty")

    if powers_mW is not None and beam_ratio is not None:
        raise ValueError("specify either powers_mW or beam_ratio, not both")
    if powers_mW is None:
        ratio = 1.0 if beam_ratio is None else float(beam_ratio)
        total = float(total_power_mW)
        if not math.isfinite(ratio) or ratio <= 0.0:
            raise ValueError("beam_ratio must be finite and positive")
        if not math.isfinite(total) or total <= 0.0:
            raise ValueError("total_power_mW must be finite and positive")
        powers = (total / (1.0 + ratio), total * ratio / (1.0 + ratio))
    else:
        powers = _pair(powers_mW, name="powers_mW")
        if any(not math.isfinite(value) or value < 0.0 for value in powers):
            raise ValueError("powers_mW must be finite and nonnegative")
        if sum(powers) <= 0.0:
            raise ValueError("total beam power must be positive")

    wavelength = float(wavelength_um)
    index = float(refractive_index)
    if wavelength <= 0.0 or index <= 0.0:
        raise ValueError("wavelength_um and refractive_index must be positive")
    k_medium = 2.0 * math.pi * index / wavelength

    channels = []
    for beam in range(2):
        theta = angles[beam]
        phi = azimuths[beam]
        k_transverse = k_medium * math.sin(theta)
        kx = k_transverse * math.cos(phi)
        ky = k_transverse * math.sin(phi)
        slope_x = paraxial_kernel_slope(
            transverse_phase_gradient_rad_per_um=kx,
            wavelength_um=wavelength,
            refractive_index=index,
        )
        slope_y = paraxial_kernel_slope(
            transverse_phase_gradient_rad_per_um=ky,
            wavelength_um=wavelength,
            refractive_index=index,
        )
        channels.append(
            BeamChannel(
                name=names[beam],
                wavelength_um=wavelength,
                power_mW=powers[beam],
                waist_x_um=waists_x[beam],
                waist_y_um=waists_y[beam],
                x0_um=float(crossing_x_um) - z_cross * slope_x,
                y0_um=float(crossing_y_um) - z_cross * slope_y,
                tilt_x_rad_per_um=kx,
                tilt_y_rad_per_um=ky,
                coherence_group=coherence_group,
            )
        )
    return channels[0], channels[1]


@dataclass(frozen=True)
class PRApertureReport:
    """Finite-beam aperture and resolution diagnostics."""

    launch_offsets_um: tuple[tuple[float, float], tuple[float, float]]
    radii_um: dict[str, tuple[tuple[float, float], tuple[float, float]]]
    boundary_margins_um: dict[str, tuple[dict[str, float], dict[str, float]]]
    samples_per_waist: tuple[tuple[float, float], tuple[float, float]]
    grating_period_um: float
    grating_samples_per_period: float
    longitudinal_steps: int
    warnings: tuple[str, ...]


def analyze_crossing_aperture(
    grid,
    channels: tuple[BeamChannel, BeamChannel],
    *,
    refractive_index: float,
    crossing_z_um: float,
    envelope_radii: float = 2.0,
    minimum_samples_per_waist: float = 6.0,
    minimum_grating_samples: float = 6.0,
    minimum_longitudinal_steps: int = 10,
    strict: bool = True,
) -> PRApertureReport:
    """Report and optionally reject inadequate finite crossing geometry.

    Boundary margins use ``envelope_radii`` times each Gaussian's 1/e²
    intensity radius; the default therefore treats the two-radius envelope as
    the closest acceptable approach to a periodic boundary.
    """

    z_cross = float(crossing_z_um)
    length = float(grid.spec.z_length_um)
    if not 0.0 <= z_cross <= length:
        raise ValueError("crossing_z_um must lie within the interaction region")
    if len(channels) != 2:
        raise ValueError("exactly two channels are required")

    planes = {"entrance": 0.0, "crossing": z_cross, "output": length}
    radii: dict[str, tuple[tuple[float, float], tuple[float, float]]] = {}
    margins: dict[str, tuple[dict[str, float], dict[str, float]]] = {}
    warnings: list[str] = []
    half_x = float(grid.spec.x_aperture_um) / 2.0
    half_y = float(grid.spec.y_aperture_um) / 2.0
    index = float(refractive_index)

    for plane_name, z_um in planes.items():
        plane_radii = []
        plane_margins = []
        for channel in channels:
            sx = paraxial_kernel_slope(
                transverse_phase_gradient_rad_per_um=channel.tilt_x_rad_per_um,
                wavelength_um=channel.wavelength_um,
                refractive_index=index,
            )
            sy = paraxial_kernel_slope(
                transverse_phase_gradient_rad_per_um=channel.tilt_y_rad_per_um,
                wavelength_um=channel.wavelength_um,
                refractive_index=index,
            )
            cx = float(channel.x0_um) + z_um * sx
            cy = float(channel.y0_um) + z_um * sy
            zrx = math.pi * index * float(channel.waist_x_um) ** 2 / float(
                channel.wavelength_um
            )
            zry = math.pi * index * float(channel.waist_y_um) ** 2 / float(
                channel.wavelength_um
            )
            wx = float(channel.waist_x_um) * math.sqrt(1.0 + (z_um / zrx) ** 2)
            wy = float(channel.waist_y_um) * math.sqrt(1.0 + (z_um / zry) ** 2)
            plane_radii.append((wx, wy))
            beam_margins = {
                "x_min": cx - envelope_radii * wx + half_x,
                "x_max": half_x - cx - envelope_radii * wx,
                "y_min": cy - envelope_radii * wy + half_y,
                "y_max": half_y - cy - envelope_radii * wy,
            }
            plane_margins.append(beam_margins)
            if min(beam_margins.values()) <= 0.0:
                warnings.append(
                    f"{channel.name} {plane_name} envelope approaches a periodic boundary"
                )
        radii[plane_name] = tuple(plane_radii)  # type: ignore[assignment]
        margins[plane_name] = tuple(plane_margins)  # type: ignore[assignment]

    samples = tuple(
        (
            float(channel.waist_x_um) / float(grid.dx_um),
            float(channel.waist_y_um) / float(grid.dy_um),
        )
        for channel in channels
    )
    if min(value for pair in samples for value in pair) < minimum_samples_per_waist:
        warnings.append("beam waist is inadequately sampled")

    delta_kx = (
        float(channels[1].tilt_x_rad_per_um)
        - float(channels[0].tilt_x_rad_per_um)
    )
    delta_ky = (
        float(channels[1].tilt_y_rad_per_um)
        - float(channels[0].tilt_y_rad_per_um)
    )
    delta_k = math.hypot(delta_kx, delta_ky)
    if delta_k == 0.0:
        grating_period = math.inf
        grating_samples = math.inf
    else:
        grating_period = 2.0 * math.pi / delta_k
        maximum_phase_step = max(
            abs(delta_kx) * float(grid.dx_um),
            abs(delta_ky) * float(grid.dy_um),
        )
        grating_samples = 2.0 * math.pi / maximum_phase_step
        if grating_samples < minimum_grating_samples:
            warnings.append("two-beam grating period is inadequately sampled")

    if int(grid.Nz) < int(minimum_longitudinal_steps):
        warnings.append("interaction region has too few longitudinal steps")
    unique_warnings = tuple(dict.fromkeys(warnings))
    if strict and unique_warnings:
        raise ValueError("; ".join(unique_warnings))
    return PRApertureReport(
        launch_offsets_um=tuple(
            (float(channel.x0_um), float(channel.y0_um)) for channel in channels
        ),  # type: ignore[arg-type]
        radii_um=radii,
        boundary_margins_um=margins,
        samples_per_waist=samples,  # type: ignore[arg-type]
        grating_period_um=grating_period,
        grating_samples_per_period=grating_samples,
        longitudinal_steps=int(grid.Nz),
        warnings=unique_warnings,
    )


__all__ = [
    "paraxial_kernel_slope",
    "crossing_beam_channels",
    "PRApertureReport",
    "analyze_crossing_aperture",
]
