from dataclasses import dataclass
from typing import Any, Protocol

@dataclass(frozen=True)
class RunnerResult:
    kind: str
    result: Any
    message: str = ""

class Runner(Protocol):
    name: str
    def run_static(self, request, **kwargs) -> RunnerResult: ...
    def continue_static(self, request, checkpoint, **kwargs) -> RunnerResult: ...
    def validate_static_continuation(self, request, checkpoint) -> None: ...
    def run_timedependent(self, request, **kwargs) -> RunnerResult: ...
    def continue_timedependent(self, request, checkpoint, additional_steps, **kwargs) -> RunnerResult: ...
    def validate_timedependent_continuation(self, request, checkpoint) -> None: ...
